name = "puppies"
author = "oljoi"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c871070149ff6f0250a557d7d23d971cad2ce406aa7ba141ce0f433175651e5"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
