name = "puppies"
author = "oljoi"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc69fb5ad3b3ce322681aaeb93de2a33a25924f7d47d55d551fd48bfdba9c33"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
