name = "puppies"
author = "oljoi"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c875c5e5680f429074e8ffcb986fae07f830f5cb90a3d3288f2a04e7c74d28c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
